//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Sudoku_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ECCI_Sudoku", ConfigurationName="Sudoku_Service.ECCI_SudokuPort")]
    public interface ECCI_SudokuPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Sudoku:ECCI_SudokuPort:checkRowRequest", ReplyAction="urn:ECCI_Sudoku:ECCI_SudokuPort:checkRowResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string checkRow(int rowNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_Sudoku:ECCI_SudokuPort:servidorEstampillaDeTiempoRequest", ReplyAction="urn:ECCI_Sudoku:ECCI_SudokuPort:servidorEstampillaDeTiempoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string servidorEstampillaDeTiempo(int columnNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ECCI_SudokuPortChannel : Sudoku.Sudoku_Service.ECCI_SudokuPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ECCI_SudokuPortClient : System.ServiceModel.ClientBase<Sudoku.Sudoku_Service.ECCI_SudokuPort>, Sudoku.Sudoku_Service.ECCI_SudokuPort {
        
        public ECCI_SudokuPortClient() {
        }
        
        public ECCI_SudokuPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ECCI_SudokuPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECCI_SudokuPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECCI_SudokuPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string checkRow(int rowNum) {
            return base.Channel.checkRow(rowNum);
        }
        
        public string servidorEstampillaDeTiempo(int columnNum) {
            return base.Channel.servidorEstampillaDeTiempo(columnNum);
        }
    }
}
